version: '3.3'
services: 
  master:
    container_name: dockerubuntu
    image: dockerindocker
    build:
      context: dockerinubuntu
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"