version: '3.3'
services: 
  master:
    container_name: ubuntudocker
    image: dockerinubuntu
    build:
      context: dockerinubuntu
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    init: true